import Head from 'next/head'
import { ScrollPage } from "react-scroll-motion";
import styled from 'styled-components'
import GridContainer from "../components/GridContainer"
import GridItem from "../components/GridItem"
import { PrimaryButton, StyledLink } from "../components/CustomButtons"
import { useAsideContext } from '../providers/AsideContext'
import CaseStudyLink from '../components/CaseStudyLink'
import pexelsFloDahm from '/public/assets/pexels-flo-dahm-699459.jpg'
import circularDownArrow from '/public/assets/circular-down-arrow.png'
import Image from 'next/future/image'
import CtaBanner from '../components/Banner';
import { Autoplay, FreeMode, Lazy, Mousewheel, Keyboard} from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';

import 'swiper/css';
import 'swiper/css/bundle';
import FeaturedServices from '../components/FeaturedServices';

const MainContainer = styled(GridContainer)` 
	padding-top: 125px; 
	padding-bottom: 125px; 
	@media screen and (max-width: ${props => props.theme.breakpoints.tablet}px){
		padding-top: 90px; 
		padding-bottom: 90px; 
	}
`

const Subtitle = styled.div` 
	color: ${props => props.theme.colors.subtitleGray};
	font-weight: 300;
	font-size: 16px;
	line-height: 24px;
`

const BlueSpan = styled.span` 
	color: ${props => props.theme.colors.blue};
`

const DarkGraySpan = styled.span` 
	color: ${props => props.theme.colors.darkestGray};
`

const Pic = styled.div` 
	position: relative;
	background: url(${pexelsFloDahm.src});
	height: 496px;
	z-index: -1;
	margin-top: -55px;	
	margin-right: -32px;	
	background-size: cover;
	background-position: bottom;
    @media screen and (max-width: ${props => props.theme.breakpoints.tablet}px){
		margin-top: 0;
		height: 360px;
		margin-right: -10px;
   	 	background-repeat: no-repeat;
		
	}
    @media screen and (max-width: ${props => props.theme.breakpoints.mobile}px){
		height: 246px;
		
	}
`

const BackgroundBorderArea = styled(GridItem)` 
	margin-right: -32px; 
	@media screen and (max-width: ${props => props.theme.breakpoints.tablet}px){
		margin-right: -10px;
	}
`

const BackPic = styled.div` 
	width: 100%;
	border: 1px solid #347DFE;
	border-top: 0;
	z-index: -2;
	padding-top: 40px;	
    @media screen and (max-width: ${props => props.theme.breakpoints.tablet}px){
		padding-top: 30px;
	}	
    @media screen and (max-width: ${props => props.theme.breakpoints.mobile}px){
		padding-top: 20px;
	}
`

const CircularArrow = styled(Image)` 
	margin-left: -24px;
	margin-top: 350px;
	position: absolute;
	@media screen and (max-width: ${props => props.theme.breakpoints.tablet}px){
		display: none;
	}	
`

export default function Home() {

	const { showContactForm } = useAsideContext();

	return (
		<>

			<Head>
				<title>Urbi Labs</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<MainContainer>
				<GridItem
					gridPosition={{
						desktop: {
							columnStart: 3,
							columnEnd: 12,
						},
						tablet: {
							columnStart: 1,
							columnEnd: 10
						},
						mobile: {
							columnStart: 1,
							columnEnd: 8
						}
					}}>
					<h1>We <BlueSpan>design and build</BlueSpan> <DarkGraySpan>website that</DarkGraySpan> turn visitors into customers.</h1>
				</GridItem>
				<GridItem
					gridPosition={{
						desktop: {
							columnStart: 3,
							columnEnd: 4,
						},
						tablet: {
							columnStart: 1,
							columnEnd: 6
						},
						mobile: {
							columnStart: 1,
							columnEnd: 6
						}
					}}
					style={{ paddingBottom: '80px' }}
				>
					<Subtitle>Our work reflects your brand and works to turn visitors into leads, customers, and subscribers.</Subtitle>
					<PrimaryButton hasArrow noBorder mt="32px" mobileMb="0" onClick={showContactForm}>Contact Us</PrimaryButton>
					<StyledLink primary mt="32px" href="/projects">Our Work</StyledLink>
				</GridItem>

				<GridItem
					gridPosition={{
						desktop: {
							columnStart: 5,
							columnEnd: 12,
						},
						tablet: {
							columnStart: 1,
							columnEnd: 10
						},
						mobile: {
							columnStart: 1,
							columnEnd: 8
						}
					}}
					style={{ zIndex: '-1' }}
				>
					<CircularArrow
						src={circularDownArrow}
						height="48px"
						width="48px"
						alt="Down Arrow"
						layout="intrinsic"
					/>
					<Pic />
				</GridItem>

				<BackgroundBorderArea
					gridPosition={{
						desktop: {
							columnStart: 6,
							columnEnd: 12,
						},
						tablet: {
							columnStart: 3,
							columnEnd: 10
						},
						mobile: {
							columnStart: 3,
							columnEnd: 8
						}
					}}
				>
					<BackPic />
				</BackgroundBorderArea>

			</MainContainer>

			<GridContainer>
				<GridItem
					gridPosition={{
						desktop: {
							columnStart: 7,
							columnEnd: 11,
						},
						tablet: {
							columnStart: 5,
							columnEnd: 9
						},
						mobile: {
							columnStart: 4,
							columnEnd: 8
						}
					}}
					style={{
						paddingBottom: '125px'
					}}>
					<h2 className="color-dark">Here's some of our work.</h2>
				</GridItem>
			</GridContainer>

			<CaseStudyLink
				index='1'
			/>

			<CaseStudyLink
				index='2'
			/>

			<CaseStudyLink
				index='3'
			/>

			<CtaBanner>
				<p className="h2 color-white text-center">
					We work with amazing companies.
				</p>

				<Swiper
					slidesPerView={'6'}
					autoplay={{
					  delay: 1,
					  disableOnInteraction: false,
					}}
					speed={8000}
					freeMode={{
						enabled: true
					}}
					modules={[Autoplay, FreeMode, Lazy]}
					loop={true}
					className="transition-linear"
				>
					<SwiperSlide>Slide 1</SwiperSlide>
					<SwiperSlide>Slide 2</SwiperSlide>
					<SwiperSlide>Slide 3</SwiperSlide>
					<SwiperSlide>Slide 4</SwiperSlide>
					<SwiperSlide>Slide 5</SwiperSlide>
					<SwiperSlide>Slide 6</SwiperSlide>
					<SwiperSlide>Slide 7</SwiperSlide>
					<SwiperSlide>Slide 8</SwiperSlide>
				</Swiper>

				<div className="text-center">
					<PrimaryButton hasArrow={true}>Let's talk</PrimaryButton>
				</div>
			</CtaBanner>

			<MainContainer>

				<GridItem
					gridPosition={{
						desktop: {
							columnStart: 3,
							columnEnd: 7,
						},
						tablet: {
							columnStart: 2,
							columnEnd: 7
						},
						mobile: {
							columnStart: 2,
							columnEnd: 7
						}
					}}>
					<h2 className="color-dark">This is what we can do for you.</h2>
				</GridItem>
				
			</MainContainer>

			<FeaturedServices/>

		</>
	)
}
