import Head from 'next/head'
import Image from 'next/image'
import { StyledLink } from '../components/CustomButtons'
import GridContainer from '../components/GridContainer'
import GridItem from '../components/GridItem'

export default function Home() {
	return (
		<div>

			<Head>
				<title>Urbi Labs</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<StyledLink primary hasArrow href="/">Home Page</StyledLink>
		</div>
	)
}
