import Head from 'next/head'
import Link from 'next/link'
import { StyledLink } from '../components/CustomButtons'

export default function Home() {
	return (
		<div>

			<Head>
				<title>Urbi Labs</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Link href='/' passHref><StyledLink primary hasArrow>Home Page</StyledLink></Link>
		</div>
	)
}
